# Generated by Django 5.0.4 on 2024-05-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
